definitions:
  config:
    /hippo:namespaces/gogreen/contentdocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 4daba63b-1b58-4b44-8643-eaf830e4aa1f
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: ec49ab05-3063-4a9f-afa4-cc0e59f9fe09
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: 869f1c4e-d5e7-420d-b5e8-64147749e210
          hipposysedit:node: true
          hipposysedit:supertype: ['gogreen:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/gogreen/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: gogreen:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: gogreen:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
          /content:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: gogreen:content
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /publicationdate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: gogreen:publicationdate
            hipposysedit:primary: false
            hipposysedit:type: Date
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: gogreen:contentdocument
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 8d72715a-ed12-49c9-925e-00276071901d
          gogreen:introduction: ''
          gogreen:publicationdate: 0001-01-01T13:00:00+01:00
          gogreen:title: ''
          hippo:related___pathreference:
            type: double
            value: []
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2014-03-25T10:56:00+01:00
          hippostdpubwf:lastModificationDate: 2014-03-25T10:56:00+01:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /gogreen:content:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          type: gogreen:contentdocument
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /content:
            jcr:primaryType: frontend:plugin
            field: content
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /publicationdate:
            jcr:primaryType: frontend:plugin
            field: publicationdate
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
