definitions:
  config:
    /hippo:namespaces/gogreen/imageset:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 0e1d4de4-0e76-4198-b2c2-089927b4b662
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: ef0117e9-e9f7-4ad6-8b1e-27ca8e604b07
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:node: true
          hipposysedit:supertype: ['hippogallery:imageset', 'hippogallery:relaxed']
          hipposysedit:uri: http://www.onehippo.org/gogreen/nt/1.0
          /filename:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:filename
            hipposysedit:type: String
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:description
            hipposysedit:type: String
          /thumbnail:
            jcr:primaryType: hipposysedit:field
            hipposysedit:autocreated: true
            hipposysedit:mandatory: true
            hipposysedit:path: hippogallery:thumbnail
            hipposysedit:primary: true
            hipposysedit:type: hippogallery:image
          /original:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:original
            hipposysedit:type: hippogallery:image
          /small:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: gogreen:small
            hipposysedit:type: hippogallery:image
          /large:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: gogreen:large
            hipposysedit:type: hippogallery:image
          /smallsquare:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: gogreen:smallsquare
            hipposysedit:type: hippogallery:image
          /mediumsquare:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: gogreen:mediumsquare
            hipposysedit:type: hippogallery:image
          /largesquare:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: gogreen:largesquare
            hipposysedit:type: hippogallery:image
          /banner:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: gogreen:banner
            hipposysedit:type: hippogallery:image
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: gogreen:imageset
          jcr:mixinTypes: ['mix:versionable', 'mix:referenceable']
          jcr:uuid: 044eaddb-8af5-49ce-9f5c-2ff2cd875109
          hippogallery:description: ''
          /hippogallery:thumbnail:
            jcr:primaryType: hippogallery:image
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/thumbnail/thumbnail.jpg
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
            jcr:encoding: UTF-8
            hippogallery:height: 94
            hippogallery:width: 94
          /hippogallery:original:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 0
            hippogallery:width: 0
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/original/original.gif
            jcr:lastModified: 1970-01-01T00:00:00Z
            jcr:mimeType: image/gif
          /gogreen:small:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 94
            hippogallery:width: 94
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/small/small.jpg
            jcr:encoding: UTF-8
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
          /gogreen:large:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 94
            hippogallery:width: 94
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/large/large.jpg
            jcr:encoding: UTF-8
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
          /gogreen:smallsquare:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 94
            hippogallery:width: 94
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/smallsquare/smallsquare.jpg
            jcr:encoding: UTF-8
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
          /gogreen:mediumsquare:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 94
            hippogallery:width: 94
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/mediumsquare/mediumsquare.jpg
            jcr:encoding: UTF-8
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
          /gogreen:largesquare:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 94
            hippogallery:width: 94
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/largesquare/largesquare.jpg
            jcr:encoding: UTF-8
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
          /gogreen:banner:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 94
            hippogallery:width: 94
            jcr:data:
              type: binary
              resource: /namespaces/gogreen/imageset/prototypes/prototype/banner/banner.jpg
            jcr:encoding: UTF-8
            jcr:lastModified: 2008-03-26T12:03:00+01:00
            jcr:mimeType: image/jpeg
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [model.compareTo, wicket.model, engine]
          frontend:services: [wicket.id]
          mode: edit
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /filename:
            jcr:primaryType: frontend:plugin
            caption: file name
            field: filename
            plugin.class: org.hippoecm.frontend.plugins.gallery.editor.FileNameDisplayPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /thumbnail:
            jcr:primaryType: frontend:plugin
            caption: thumbnail
            field: thumbnail
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /original:
            jcr:primaryType: frontend:plugin
            caption: original
            field: original
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /small:
            jcr:primaryType: frontend:plugin
            caption: small
            field: small
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /large:
            jcr:primaryType: frontend:plugin
            caption: large
            field: large
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /smallsquare:
            jcr:primaryType: frontend:plugin
            caption: smallsquare
            field: smallsquare
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /mediumsquare:
            jcr:primaryType: frontend:plugin
            caption: mediumsquare
            field: mediumsquare
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /largesquare:
            jcr:primaryType: frontend:plugin
            caption: largesquare
            field: largesquare
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /banner:
            jcr:primaryType: frontend:plugin
            caption: banner
            field: banner
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
