definitions:
  config:
    /hippo:namespaces/gogreen/basedocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 01a3a079-1dfa-4d89-ab71-cb87ff13e504
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 1219324b-cf74-4b3f-8869-f00adfe65e6d
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:supertype: ['hippo:document', 'hippostdpubwf:document', 'hippostd:publishableSummary']
          hipposysedit:uri: http://www.onehippo.org/gogreen/nt/1.0
