definitions:
  config:
    /hippo:configuration/hippo:frontend/cms/cms-services/galleryProcessorService/gogreen:small:
      jcr:primaryType: frontend:pluginconfig
      height: 224
      upscaling: false
      width: 491
      compression: 1.0
      optimize: quality
    /hippo:configuration/hippo:frontend/cms/cms-services/galleryProcessorService/gogreen:large:
      jcr:primaryType: frontend:pluginconfig
      height: 302
      upscaling: false
      width: 663
      compression: 1.0
      optimize: quality
    /hippo:configuration/hippo:frontend/cms/cms-services/galleryProcessorService/gogreen:smallsquare:
      jcr:primaryType: frontend:pluginconfig
      height: 233
      upscaling: false
      width: 233
      compression: 1.0
      optimize: quality
    /hippo:configuration/hippo:frontend/cms/cms-services/galleryProcessorService/gogreen:mediumsquare:
      jcr:primaryType: frontend:pluginconfig
      height: 313
      upscaling: false
      width: 313
      compression: 1.0
      optimize: quality
    /hippo:configuration/hippo:frontend/cms/cms-services/galleryProcessorService/gogreen:largesquare:
      jcr:primaryType: frontend:pluginconfig
      height: 663
      upscaling: false
      width: 663
      compression: 1.0
      optimize: quality
    /hippo:configuration/hippo:frontend/cms/cms-services/galleryProcessorService/gogreen:banner:
      jcr:primaryType: frontend:pluginconfig
      height: 250
      upscaling: false
      width: 1070
      compression: 1.0
      optimize: quality
