definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:workspace/hst:sitemenus:
      jcr:primaryType: hst:sitemenus
      /main:
        jcr:primaryType: hst:sitemenu
        hst:lastmodified: 2017-06-27T10:28:02.919-07:00
        /Home:
          jcr:primaryType: hst:sitemenuitem
          hst:referencesitemapitem: root
          hst:repobased: false
        /News:
          jcr:primaryType: hst:sitemenuitem
          hst:referencesitemapitem: news
          hst:repobased: false
        /About:
          jcr:primaryType: hst:sitemenuitem
          hst:referencesitemapitem: about
          hst:repobased: false
          /Quick Facts:
            jcr:primaryType: hst:sitemenuitem
            hst:referencesitemapitem: content/quick-facts.html
          /Terms & Conditions:
            jcr:primaryType: hst:sitemenuitem
            hst:referencesitemapitem: content/terms--conditions.html
        /Products:
          jcr:primaryType: hst:sitemenuitem
          hst:referencesitemapitem: products
