definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:workspace/hst:pages:
      jcr:primaryType: hst:pages
      /about-contentpage:
        jcr:primaryType: hst:component
        hst:lastmodified: 2017-06-27T09:50:18.998-07:00
        hst:referencecomponent: hst:abstractpages/twocolumns
        /main:
          jcr:primaryType: hst:component
          /left:
            jcr:primaryType: hst:containercomponent
            hst:label: Content Page Main
            hst:lastmodified: 2017-06-27T10:26:26.095-07:00
            hst:xtype: hst.vbox
            /simplecontent:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsDocumentComponent
              hst:iconpath: images/essentials/catalog-component-icons/simple-content.png
              hst:label: Simple Content
              hst:parameternames: [document, org.hippoecm.hst.core.component.template]
              hst:parametervalues: [about/about, 'webfile:/freemarker/hstdefault/contentpage-main.ftl']
              hst:template: contentpage-main
              hst:xtype: hst.item
          /right:
            jcr:primaryType: hst:component
            hst:template: twocolumns-right-menu
            hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
            hst:parameternames: [menu]
            hst:parametervalues: [main]
